# Generated by Django 2.1 on 2018-08-05 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20180805_2242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='created_date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='modified_date',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='devicereport',
            old_name='created_date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='devicereport',
            old_name='modified_date',
            new_name='modified',
        ),
    ]
