# Generated by Django 2.1 on 2018-08-05 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20180805_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicereport',
            name='last_update',
        ),
    ]
