# Generated by Django 2.1 on 2018-08-17 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Vendor'),
        ),
    ]
