# Generated by Django 2.1 on 2018-08-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20180818_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='status',
            field=models.CharField(default='Down', max_length=15),
        ),
        migrations.AlterField(
            model_name='device',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=20, default=0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='device',
            name='long',
            field=models.DecimalField(blank=True, decimal_places=20, default=0, max_digits=50),
        ),
    ]
